# This file is part of the CMS Kernel library.
#
# Copyright (c) 2016-2017 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s.cms_kernel.application.command_bus:
        class: LIN3S\SharedKernel\Infrastructure\Application\SimpleBus\SimpleBusCommandBus
        arguments:
            - "@command_bus"

# Event recorder that communicates command bus with the SimpleBus's event bus and
# Doctrine events publishing the recorded events of the aggregate root.
    lin3s.cms_kernel.application.simple_bus.event_recorder.aggregate_root:
        class: LIN3S\SharedKernel\Infrastructure\Event\SimpleBus\EventRecorder\Doctrine\ORM\AggregateRootEventRecorder
        public: false
        tags:
            - { name: event_recorder }
            - { name: doctrine.event_subscriber }
