# This file is part of the CMS Kernel package.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s.cms_kernel.application.data_transformer.menu.menu_item_dto:
        class: LIN3S\CMSKernel\Application\DataTransformer\Menu\MenuItemDTODataTransformer
        public: false

    lin3s_cms.menu_item_dto_data_transformer:
        alias: lin3s.cms_kernel.application.data_transformer.menu.menu_item_dto
