# This file is part of the CMS Kernel package.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s.cms_kernel.form_types.menu_tree:
        class: LIN3S\CMSKernel\Infrastructure\Symfony\Form\Type\MenuTreeType
        arguments:
            - "@lin3s.cms_kernel.application.query.menu.menu_of_id"
        tags:
            - name: "form.type"

    lin3s.cms_kernel.form_types.add_menu:
        class: LIN3S\CMSKernel\Infrastructure\Symfony\Form\Type\Menu\AddMenuType
        arguments:
            - "@translator"
        tags:
            - name: "form.type"
