# This file is part of the CMS Kernel package.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s.cms_kernel.application.query.menu.menu_of_id:
        class: LIN3S\CMSKernel\Application\Query\Menu\MenuOfIdHandler
        arguments:
            - "@lin3s.cms_kernel.infrastructure.persistence.doctrine.orm.repository.menu"
            - "@lin3s.cms_kernel.application.data_transformer.menu.menu_dto"
        tags:
            -
                name: query_handler
                handles: LIN3S\CMSKernel\Application\Query\Menu\MenuOfIdQuery

    lin3s.cms_kernel.application.query.menu.menu_of_code:
        class: LIN3S\CMSKernel\Application\Query\Menu\MenuOfCodeHandler
        arguments:
            - "@lin3s.cms_kernel.infrastructure.persistence.doctrine.orm.repository.menu"
            - "@lin3s.cms_kernel.application.data_transformer.menu.menu_dto"
        tags:
            -
                name: query_handler
                handles: LIN3S\CMSKernel\Application\Query\Menu\MenuOfCodeQuery
