# This file is part of the CMS Kernel package.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s.cms_kernel.twig.menu_renderer:
        class: LIN3S\CMSKernel\Infrastructure\Symfony\Bundle\Twig\MenuRendererFunction
        public: false
        arguments:
            - "@request_stack"
            - "@lin3s.cms_kernel.application.query.menu.menu_of_code"
        tags:
            -
                name: twig.extension
